# Generated by Django 4.1.3 on 2022-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='okk', upload_to='photo'),
            preserve_default=False,
        ),
    ]
